Type: Class
Attributes:
  - Structure
  - DefaultConstructor
  - Destructor
  - Move
Namespace: Graphics
Properties:
  - Name: SourcePath
    Type: System.Path
    Attributes:
      - Serialize
  - Name: SourceName
    Type: StringID
    Attributes:
      - Serialize
  - Name: Vertices
    Type: Array<Vertex>
  - Name: Faces
    Type: Array<Face>
  - Attributes:
      - Incomplete
    Name: Data
    Type: InplaceStorage<MeshPrivateData, 16, 8, false>
  - Name: IsCompiled
    Type: bool
